name: 'production-centralus-aks'
on:
  push:
    branches:
      - master
    paths:
      - 'production/centralus/**'
  pull_request:
    paths:
      - 'production/centralus/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_aks_service_principal_id: ${{ secrets.TF_VAR_aks_service_principal_id }}
      TF_VAR_active_directory_client_app_id     : ${{ secrets.TF_VAR_active_directory_client_app_id      }}
      TF_VAR_active_directory_server_app_id     : ${{ secrets.TF_VAR_active_directory_server_app_id      }}
      TF_VAR_ssh_public_key: ${{ secrets.TF_VAR_ssh_public_key }}
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './production/centralus'
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './production/centralus'
          args: '-backend-config="./backend.tfvars"'
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './production/centralus'
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        if: github.ref != 'refs/heads/master'
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './production/centralus'
          tf_actions_comment: true
          args: '-var-file="./terraform.tfvars"'
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_active_directory_server_app_secret : ${{ secrets.TF_VAR_active_directory_server_app_secret  }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_aks_service_principal_secret: ${{ secrets.TF_VAR_aks_service_principal_secret }}
      - name: 'Terraform Apply'
        uses: hashicorp/terraform-github-actions@master
        if: github.ref == 'refs/heads/master'
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './production/centralus'
          tf_actions_comment: true
          args: '-var-file="./terraform.tfvars"'
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          TF_VAR_active_directory_server_app_secret : ${{ secrets.TF_VAR_active_directory_server_app_secret  }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_aks_service_principal_secret: ${{ secrets.TF_VAR_aks_service_principal_secret }}

      #### Once cluster is up and running, we want to create kubernetes resources in following

      - name: 'Terraform Format - kubernetes'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'fmt'
      - name: 'Terraform Init - kubernetes'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './production/centralus/kubernetes'
          args: '-backend-config="./backend.tfvars"'
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      - name: 'Terraform Validate - kubernetes'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'validate'
          tf_actions_comment: true
          tf_actions_working_dir: './production/centralus/kubernetes'
      - name: 'Terraform Apply - kubernetes'
        uses: hashicorp/terraform-github-actions@master
        if: github.ref == 'refs/heads/master'
        with:
          tf_actions_version: 0.12.20
          tf_actions_subcommand: 'apply'
          tf_actions_comment: true
          tf_actions_working_dir: './production/centralus/kubernetes'
          args: '-var-file="./terraform.tfvars"'
        env:
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}